title: Alexis Nava
description: Alexis Nava's Personal Website
baseurl: ""

username: Alexis Nava
typing_text: Software Engineer

email: alexis.nava.s@outlook.com
telegram_username: null
linkedin_username: alexis-nava
github_username: Nanomixer98
facebook_username: null
instagram_username: null
viber_number: null

show_aboutme_card: false
about_me_title: About Me
about_me_description: <empty>

show_skills_card: true
skills_title: Skills

show_timeline_card: true
timeline_title: Experience & Education
cv_download_link: https://resume.io/r/L57OtJ63W

show_projects_card: true
show_projects: false
projects_title: Work Projects
show_os_projects: true
os_projects_title: Portfolio Projects

show_contact_card: true
contact_title: Contacts
contact_description: If you liked my profile or would like to know more about me, feel free to contact me!

repository: Nanomixer98/Nanomixer98.github.io
github_pages:
  - sorting_algos
  - character_encoder
  - Nanomixer98.github.io

projects:
  sort_by: stars
  exclude:
    archived: true
    forks: true
    projects:
      - insolitum

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
    "README_INFO.md",
  ]
